import type {SystemMapDataset} from "./systemMap.types.ts";

/**
 * Hand-curated System Map for the eCommerce (catalog) module only.
 * Marketplace lives at /eCommerce/marketplacesystemmap.
 */

export const ECOMMERCE_SYSTEM_MAP: SystemMapDataset = {
    clusters: ["catalog", "ordering", "payments", "escrow", "shared"],
    nodes: [
        {
            id: "CmsBlock",
            label: "CmsBlock",
            cluster: "catalog",
            module: "eCommerce",
            description: "Storefront CMS content blocks for the public shop.",
            keyFields: ["key", "title", "body", "status"],
            apiPath: "/api/eCommerce/cmsBlock",
            panelRoute: "/eCommerce/cmsblocks",
            position: {x: 40, y: 40},
        },
        {
            id: "Category",
            label: "Category",
            cluster: "shared",
            module: "shared",
            description: "Taxonomy tree for catalog products (also reused by marketplace).",
            keyFields: ["name", "slug", "parent", "path"],
            apiPath: "/api/eCommerce/category",
            panelRoute: "/eCommerce/categories",
            position: {x: 280, y: 40},
        },
        {
            id: "Product",
            label: "Product",
            cluster: "catalog",
            module: "eCommerce",
            description:
                "Sellable catalog item — physical, digital, service, variable, bundle, or gift card.",
            keyFields: ["type", "title", "slug", "pricing", "sku", "status", "vendor"],
            apiPath: "/api/eCommerce/product",
            panelRoute: "/eCommerce/products",
            actions: ["create", "update", "publish", "unpublish"],
            position: {x: 40, y: 180},
        },
        {
            id: "Collection",
            label: "Collection",
            cluster: "catalog",
            module: "eCommerce",
            description: "Manual or rule-driven merchandising collection.",
            keyFields: ["title", "type", "rules", "products"],
            apiPath: "/api/eCommerce/collection",
            panelRoute: "/eCommerce/collections",
            position: {x: 280, y: 180},
        },
        {
            id: "ProductVariant",
            label: "ProductVariant",
            cluster: "catalog",
            module: "eCommerce",
            description: "SKU-level variant of a variable product (size, color, etc.).",
            keyFields: ["product", "price", "sku", "attributes"],
            apiPath: "/api/eCommerce/productVariant",
            panelRoute: "/eCommerce/productvariants",
            position: {x: 40, y: 320},
        },
        {
            id: "ProductReview",
            label: "ProductReview",
            cluster: "payments",
            module: "eCommerce",
            description: "Buyer rating and review on a catalog product.",
            keyFields: ["product", "user", "rating", "body"],
            apiPath: "/api/eCommerce/productReview",
            panelRoute: "/eCommerce/productreviews",
            position: {x: 280, y: 320},
        },
        {
            id: "ProductAttribute",
            label: "ProductAttribute",
            cluster: "catalog",
            module: "eCommerce",
            description: "Configurable attribute definition used by variants.",
            keyFields: ["name", "options"],
            apiPath: "/api/eCommerce/productAttribute",
            panelRoute: "/eCommerce/productattributes",
            position: {x: 40, y: 460},
        },
        {
            id: "PricingRule",
            label: "PricingRule",
            cluster: "catalog",
            module: "eCommerce",
            description: "Catalog pricing adjustments by product, category, or customer group.",
            keyFields: ["name", "scope", "adjustment", "priority"],
            apiPath: "/api/eCommerce/pricingRule",
            panelRoute: "/eCommerce/pricingrules",
            position: {x: 280, y: 460},
        },
        {
            id: "Warehouse",
            label: "Warehouse",
            cluster: "catalog",
            module: "eCommerce",
            description: "Physical stock location that owns inventory rows.",
            keyFields: ["name", "address", "active"],
            apiPath: "/api/eCommerce/warehouse",
            panelRoute: "/eCommerce/warehouses",
            position: {x: 40, y: 600},
        },
        {
            id: "Inventory",
            label: "Inventory",
            cluster: "catalog",
            module: "eCommerce",
            description: "On-hand / reserved quantity per product (and optional variant) at a warehouse.",
            keyFields: ["product", "variant", "warehouse", "onHand", "reserved"],
            apiPath: "/api/eCommerce/inventory",
            panelRoute: "/eCommerce/inventories",
            position: {x: 280, y: 600},
        },
        {
            id: "InventoryMovement",
            label: "InventoryMovement",
            cluster: "catalog",
            module: "eCommerce",
            description: "Audit trail of stock changes (restock, sale, return, adjustment).",
            keyFields: ["inventory", "type", "quantity", "reason"],
            position: {x: 280, y: 740},
        },
        {
            id: "CustomerAddress",
            label: "CustomerAddress",
            cluster: "ordering",
            module: "eCommerce",
            description: "Saved buyer shipping/billing addresses.",
            keyFields: ["user", "line1", "city", "country", "isDefault"],
            apiPath: "/api/eCommerce/customerAddress",
            panelRoute: "/eCommerce/customeraddresses",
            position: {x: 560, y: 40},
        },
        {
            id: "CustomerGroup",
            label: "CustomerGroup",
            cluster: "ordering",
            module: "eCommerce",
            description: "Buyer segments used by pricing rules and promotions.",
            keyFields: ["name", "members"],
            apiPath: "/api/eCommerce/customerGroup",
            panelRoute: "/eCommerce/customergroups",
            position: {x: 800, y: 40},
        },
        {
            id: "Discount",
            label: "Discount",
            cluster: "ordering",
            module: "eCommerce",
            description: "Percent, fixed, free-shipping, or BXGY promotion codes.",
            keyFields: ["code", "type", "value", "rules", "status"],
            apiPath: "/api/eCommerce/discount",
            panelRoute: "/eCommerce/discounts",
            position: {x: 800, y: 160},
        },
        {
            id: "Cart",
            label: "Cart",
            cluster: "ordering",
            module: "eCommerce",
            description: "Authenticated shopper cart with line items, discounts, and gift-card credit.",
            keyFields: ["user", "company", "items[]", "discounts", "giftCard", "totals"],
            apiPath: "/api/eCommerce/cart",
            actions: ["addItem", "updateItem", "removeItem", "applyDiscount", "applyGiftCard"],
            position: {x: 560, y: 180},
        },
        {
            id: "GiftCard",
            label: "GiftCard",
            cluster: "ordering",
            module: "eCommerce",
            description: "Store credit instrument applied at cart/checkout.",
            keyFields: ["code", "balance", "currency", "status"],
            apiPath: "/api/eCommerce/giftCard",
            panelRoute: "/eCommerce/giftcards",
            position: {x: 800, y: 280},
        },
        {
            id: "Checkout",
            label: "Checkout",
            cluster: "ordering",
            module: "eCommerce",
            description:
                "Cart snapshot through address → shipping → Stripe PaymentIntent → confirm with inventory reservation.",
            keyFields: ["cart", "address", "shippingRate", "tax", "paymentIntent", "reservations", "status"],
            apiPath: "/api/eCommerce/checkout",
            actions: ["init", "address", "shipping", "payment", "confirm"],
            position: {x: 560, y: 360},
        },
        {
            id: "TaxZone",
            label: "TaxZone",
            cluster: "ordering",
            module: "eCommerce",
            description: "Geo tax rules used during checkout address step.",
            keyFields: ["name", "regions", "rates"],
            apiPath: "/api/eCommerce/taxZone",
            panelRoute: "/eCommerce/taxzones",
            position: {x: 800, y: 400},
        },
        {
            id: "ShippingZone",
            label: "ShippingZone",
            cluster: "ordering",
            module: "eCommerce",
            description: "Geo shipping rates offered at checkout.",
            keyFields: ["name", "regions", "rates"],
            apiPath: "/api/eCommerce/shippingZone",
            panelRoute: "/eCommerce/shippingzones",
            position: {x: 800, y: 520},
        },
        {
            id: "ProductOrder",
            label: "ProductOrder",
            cluster: "ordering",
            module: "eCommerce",
            description: "Catalog order after successful checkout — fulfillment and payment lifecycle.",
            keyFields: ["orderNumber", "customer", "items", "totals", "paymentStatus", "fulfillmentStatus"],
            apiPath: "/api/eCommerce/productOrder",
            panelRoute: "/eCommerce/productorders",
            actions: ["confirm", "markProcessing", "ship", "cancel", "refund"],
            position: {x: 560, y: 540},
        },
        {
            id: "PaymentWebhookEvent",
            label: "PaymentWebhookEvent",
            cluster: "payments",
            module: "eCommerce",
            description: "Idempotent Stripe webhook event log.",
            keyFields: ["eventId", "type", "processedAt"],
            apiPath: "/api/eCommerce/paymentsWebhook/stripe",
            position: {x: 1040, y: 220},
        },
        {
            id: "PaymentTransaction",
            label: "PaymentTransaction",
            cluster: "payments",
            module: "eCommerce",
            description: "Gateway payment record linked to checkout and/or product order.",
            keyFields: ["gateway", "type", "status", "amount", "checkout", "order"],
            apiPath: "/api/eCommerce/paymentTransaction",
            panelRoute: "/eCommerce/paymenttransactions",
            position: {x: 1040, y: 360},
        },
        {
            id: "Fulfillment",
            label: "Fulfillment",
            cluster: "payments",
            module: "eCommerce",
            description: "Shipment / tracking record for a product order.",
            keyFields: ["order", "carrier", "trackingNumber", "status"],
            apiPath: "/api/eCommerce/fulfillment",
            panelRoute: "/eCommerce/fulfillments",
            position: {x: 1040, y: 540},
        },
        {
            id: "ReturnRequest",
            label: "ReturnRequest",
            cluster: "payments",
            module: "eCommerce",
            description: "Return, exchange, or refund request against a product order.",
            keyFields: ["order", "reason", "status", "items"],
            apiPath: "/api/eCommerce/returnRequest",
            panelRoute: "/eCommerce/returnrequests",
            position: {x: 1040, y: 680},
        },
        {
            id: "DigitalDelivery",
            label: "DigitalDelivery",
            cluster: "payments",
            module: "eCommerce",
            description: "Download entitlements issued after paid digital product orders.",
            keyFields: ["order", "product", "token", "expiresAt"],
            position: {x: 800, y: 680},
        },
        {
            id: "EscrowTransaction",
            label: "EscrowTransaction",
            cluster: "escrow",
            module: "eCommerce",
            description:
                "Hold / release / refund / platform fee ledger owned by eCommerce. Consumed by marketplace orders (see Marketplace System Map).",
            keyFields: ["order", "type", "amount", "gatewayIds", "status"],
            apiPath: "/api/finance/escrowTransaction",
            panelRoute: "/finance/escrowdashboard",
            actions: ["createEscrowHold", "createEscrowReleaseAndFee", "refund"],
            position: {x: 560, y: 760},
        },
        {
            id: "OrderMilestone",
            label: "OrderMilestone",
            cluster: "escrow",
            module: "eCommerce",
            description: "Milestone steps for escrowed marketplace work (schema lives here).",
            keyFields: ["order", "title", "amount", "status", "dueAt"],
            apiPath: "/api/eCommerceMarketplace/orderMilestone",
            position: {x: 800, y: 820},
        },
        {
            id: "OrderDelivery",
            label: "OrderDelivery",
            cluster: "escrow",
            module: "eCommerce",
            description: "Provider delivery submission schema used by marketplace orders.",
            keyFields: ["order", "files", "message", "status"],
            apiPath: "/api/eCommerceMarketplace/orderDelivery",
            position: {x: 560, y: 900},
        },
        {
            id: "OrderRevision",
            label: "OrderRevision",
            cluster: "escrow",
            module: "eCommerce",
            description: "Buyer revision request schema (max 3) used by marketplace orders.",
            keyFields: ["order", "message", "status"],
            apiPath: "/api/eCommerceMarketplace/orderRevision",
            position: {x: 800, y: 960},
        },
    ],
    edges: [
        {id: "e-pv-p", source: "ProductVariant", target: "Product", label: "belongs to"},
        {id: "e-p-cat", source: "Product", target: "Category", label: "categorized"},
        {id: "e-p-col", source: "Product", target: "Collection", label: "in"},
        {id: "e-inv-p", source: "Inventory", target: "Product", label: "stocks"},
        {id: "e-inv-pv", source: "Inventory", target: "ProductVariant", label: "variant"},
        {id: "e-inv-wh", source: "Inventory", target: "Warehouse", label: "at"},
        {id: "e-im-inv", source: "InventoryMovement", target: "Inventory", label: "audits"},
        {id: "e-pr-p", source: "ProductReview", target: "Product", label: "reviews"},
        {id: "e-prule-p", source: "PricingRule", target: "Product", label: "prices"},
        {id: "e-cg-pr", source: "CustomerGroup", target: "PricingRule", label: "targets"},
        {id: "e-cart-p", source: "Cart", target: "Product", label: "items"},
        {id: "e-cart-d", source: "Cart", target: "Discount", label: "applies"},
        {id: "e-cart-gc", source: "Cart", target: "GiftCard", label: "credits"},
        {id: "e-co-cart", source: "Checkout", target: "Cart", label: "from"},
        {id: "e-co-tax", source: "Checkout", target: "TaxZone", label: "tax"},
        {id: "e-co-ship", source: "Checkout", target: "ShippingZone", label: "shipping"},
        {id: "e-co-addr", source: "Checkout", target: "CustomerAddress", label: "address"},
        {id: "e-po-co", source: "ProductOrder", target: "Checkout", label: "created from"},
        {id: "e-po-p", source: "ProductOrder", target: "Product", label: "items"},
        {id: "e-pt-co", source: "PaymentTransaction", target: "Checkout", label: "charges"},
        {id: "e-pt-po", source: "PaymentTransaction", target: "ProductOrder", label: "settles"},
        {id: "e-wh-pt", source: "PaymentWebhookEvent", target: "PaymentTransaction", label: "updates"},
        {id: "e-ful-po", source: "Fulfillment", target: "ProductOrder", label: "ships"},
        {id: "e-rr-po", source: "ReturnRequest", target: "ProductOrder", label: "returns"},
        {id: "e-dd-po", source: "DigitalDelivery", target: "ProductOrder", label: "entitles"},
        {id: "e-ms-esc", source: "OrderMilestone", target: "EscrowTransaction", label: "milestones"},
        {id: "e-od-esc", source: "OrderDelivery", target: "EscrowTransaction", label: "alongside"},
        {id: "e-or-esc", source: "OrderRevision", target: "EscrowTransaction", label: "alongside"},
    ],
    flows: [
        {
            id: "catalog-checkout",
            title: "Catalog checkout",
            summary:
                "Browse → cart → checkout (address, tax, shipping, Stripe PI) → confirm with inventory reservation → webhook settles → fulfill / digital delivery.",
            module: "eCommerce",
            steps: [
                {
                    id: "cc-browse",
                    label: "Browse catalog",
                    description: "Public shopProducts / shopProduct / shopTaxonomy",
                    detail: "Storefront reads published products, categories, and CMS blocks.",
                    position: {x: 0, y: 80},
                },
                {
                    id: "cc-cart",
                    label: "Cart",
                    description: "Add / update / discount / gift card",
                    detail: "/api/eCommerce/cart — auth-only cart mutations.",
                    position: {x: 220, y: 80},
                },
                {
                    id: "cc-init",
                    label: "Checkout init",
                    description: "Snapshot cart into Checkout",
                    detail: "checkout.init creates a Checkout document from the live cart.",
                    position: {x: 440, y: 80},
                },
                {
                    id: "cc-address",
                    label: "Address",
                    description: "Tax + shipping rates",
                    detail: "Applies TaxZone and ShippingZone rates for the destination.",
                    position: {x: 660, y: 80},
                },
                {
                    id: "cc-payment",
                    label: "Payment",
                    description: "Stripe PaymentIntent",
                    detail: "Creates PI + pending PaymentTransaction.",
                    position: {x: 880, y: 80},
                },
                {
                    id: "cc-confirm",
                    label: "Confirm",
                    description: "Reserve inventory → ProductOrder",
                    detail: "Inventory reserved; ProductOrder created; waits for paid charge when online.",
                    position: {x: 1100, y: 80},
                },
                {
                    id: "cc-webhook",
                    label: "Webhook",
                    description: "Mark paid, consume reservations",
                    detail: "POST /api/eCommerce/paymentsWebhook/stripe — idempotent settle.",
                    position: {x: 1320, y: 80},
                },
                {
                    id: "cc-fulfill",
                    label: "Fulfill",
                    description: "Ship / digital / gift extras",
                    detail: "Fulfillment, DigitalDelivery, gift-card issuance as needed.",
                    position: {x: 1540, y: 80},
                },
            ],
            edges: [
                {id: "f-cc-1", source: "cc-browse", target: "cc-cart"},
                {id: "f-cc-2", source: "cc-cart", target: "cc-init"},
                {id: "f-cc-3", source: "cc-init", target: "cc-address"},
                {id: "f-cc-4", source: "cc-address", target: "cc-payment", label: "shipping selected"},
                {id: "f-cc-5", source: "cc-payment", target: "cc-confirm"},
                {id: "f-cc-6", source: "cc-confirm", target: "cc-webhook", label: "Stripe event"},
                {id: "f-cc-7", source: "cc-webhook", target: "cc-fulfill"},
            ],
        },
    ],
    capabilities: [
        {
            id: "eCommerce",
            title: "eCommerce (catalog)",
            summary:
                "Full catalog shop: products, inventory, cart, Stripe checkout, product orders, fulfillments, returns, discounts, gift cards, tax/shipping, analytics. Also owns the escrow ledger used by Marketplace.",
            offers: [
                {
                    title: "Catalog & merchandising",
                    description: "Products, variants, attributes, categories, collections, pricing rules, CMS blocks.",
                },
                {
                    title: "Inventory",
                    description: "Warehouses, stock levels, reservations at checkout, movement audit trail.",
                },
                {
                    title: "Cart → checkout → order",
                    description: "Authenticated cart, multi-step checkout, Stripe PaymentIntent, ProductOrder lifecycle.",
                },
                {
                    title: "Post-purchase ops",
                    description: "Fulfillments, returns, digital delivery, gift cards, product reviews.",
                },
                {
                    title: "Escrow ledger",
                    description:
                        "EscrowTransaction + milestones/deliveries/revisions — consumed by Marketplace orders (see Marketplace System Map).",
                },
            ],
            apis: [
                "/api/eCommerce/product",
                "/api/eCommerce/cart",
                "/api/eCommerce/checkout",
                "/api/eCommerce/productOrder",
                "/api/eCommerce/paymentTransaction",
                "/api/finance/escrowTransaction",
                "/api/eCommerce/fulfillment",
                "/api/eCommerce/inventory",
                "/api/eCommerce/analytics",
            ],
            crons: [
                "Abandoned cart",
                "Checkout expiry",
                "Low stock alerts",
                "Scheduled publish",
                "Collection rebuild",
                "Order auto-complete",
            ],
            publicRoutes: ["/", "/products", "/product", "/cart", "/checkout", "/account/orders", "/account/giftcards"],
        },
    ],
};
